### ISSUE TITLE
Allow spin to run in sub-directories/easier to spot that your error is caused by being in a sub-directory

### ISSUE THREAD

**Issue by betatim** [scientific-python/spin#230]
Sometimes I am in a sub-directory of my repository and run `spin doc` (or some other command).

Currently this fails:
```
$ spin docs --no-plot
Error: need valid configuration in [.spin.toml], [spin.toml], or [pyproject.toml]
See https://github.com/scientific-python/spin/blob/main/README.md

Usage: spin [OPTIONS] COMMAND [ARGS]...
Try 'spin --help' for help.

Error: No such command 'docs'.
```

In the first instance this makes me think "ah, it must be `doc` not `docs`", which also fails. Mostly because I only read the "No such command" part of the output.

Two ideas:
1. what about making it so that `spin` works from any sub-directory, like `git`?
2. can we have spin exit after printing the first two lines? That seems like the message people should read and the usage info + "no such command" output is a distraction/red herring.

**Comment by stefanv** [comment]
I thought about this a bit, and I see two options:

(a) We only provide a more helpful error message, such as "Did you mean to run this from `../..`?"
(b) We add a utility function that a command can use to figure out where it was called from, and where the root is. This is necessary because not all commands *can* run in the current directory: `spin test` must be run from root, typically, while `spin run` can be called in the current directory without a problem.

**Comment by betatim** [comment]
Maybe improving the error message is a "no brainer" that would make life better already. Then we can still think about allowing running from sub-directories or not

**Comment by stefanv** [comment]
@betatim Please see https://github.com/scientific-python/spin/pull/232
